#!/usr/bin/env node
'use strict';

// Forge tool: collate
// Regenerate markdown views from the JSON store. Deterministic — no AI needed.
// Usage: collate [SPRINT_ID] [--dry-run]

const fs = require('fs');
const path = require('path');
const store = require('./store.cjs');

const DRY_RUN = process.argv.includes('--dry-run');
const SPRINT_ARG = process.argv.slice(2).find(a => !a.startsWith('--'));
const cwd = process.cwd();
const GENERATED = '<!-- GENERATED by forge/collate — do not edit manually -->';

// --- Helpers ---

function writeFile(filePath, content) {
  if (DRY_RUN) { console.log(`[dry-run] would write: ${path.relative(cwd, filePath)}`); return; }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function statusBadge(status) {
  const map = {
    committed: '✅', approved: '✅', completed: '✅',
    'retrospective-done': '✅', fixed: '✅', verified: '✅',
    implemented: '🔧', implementing: '🔧',
    'in-progress': '🔵', active: '🔵',
    'plan-approved': '📋', 'review-approved': '📋', planned: '📋',
    planning: '📝', draft: '📝',
    triaged: '🟡', 'partially-completed': '🟡',
    'plan-revision-required': '🔄', 'code-revision-required': '🔄',
    reported: '🔴', blocked: '🚫', escalated: '⚠️',
    abandoned: '❌',
  };
  const badge = map[status];
  return badge ? `${badge} ${status}` : status;
}

// Resolve a directory name under `base` by trying candidates in order.
// Returns the first candidate whose directory exists. If none exist,
// attempts a numeric glob: finds the first alphabetically-sorted dir
// in `base` whose first integer matches the first integer in the last
// candidate. Falls back to the last candidate if no match is found.
function resolveDir(base, ...candidates) {
  for (const c of candidates) {
    if (fs.existsSync(path.join(base, c))) return c;
  }
  // Numeric glob fallback
  const last = candidates[candidates.length - 1];
  const numMatch = last.match(/\d+/);
  if (numMatch && fs.existsSync(base)) {
    const target = parseInt(numMatch[0], 10);
    const dirs = fs.readdirSync(base).sort();
    for (const d of dirs) {
      const m = d.match(/\d+/);
      if (m && parseInt(m[0], 10) === target) return d;
    }
  }
  return last;
}

function padTable(rows) {
  if (rows.length === 0) return '';
  const cols = rows[0].length;
  const widths = Array.from({ length: cols }, (_, i) => Math.max(...rows.map(r => String(r[i] ?? '').length)));
  return rows.map((r, ri) => {
    const cells = r.map((c, i) => String(c ?? '').padEnd(widths[i]));
    const line = `| ${cells.join(' | ')} |`;
    if (ri === 0) return line + '\n' + `| ${widths.map(w => '-'.repeat(w)).join(' | ')} |`;
    return line;
  }).join('\n');
}

// --- Load store ---
function readConfig() {
  const p = path.join(cwd, '.forge', 'config.json');
  if (!fs.existsSync(p)) { console.error('Error: .forge/config.json not found'); process.exit(1); }
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch (e) {
    console.error(`Error: .forge/config.json is not valid JSON: ${e.message}`); process.exit(1);
  }
}

const config = readConfig();
const storePath  = config.paths?.store || '.forge/store';
const engPath    = config.paths?.engineering || 'engineering';
const projectName = config.project?.name || config.project?.prefix || 'Project';

const storeRoot = path.join(cwd, storePath);
const engRoot   = path.join(cwd, engPath);

const allSprints = store.listSprints()
  .sort((a, b) => a.sprintId.localeCompare(b.sprintId));
const allTasks   = store.listTasks();
const allBugs    = store.listBugs();
const allFeatures= store.listFeatures()
  .sort((a, b) => (a.id || '').localeCompare(b.id || ''));

// Group tasks by sprint
const tasksBySprint = {};
for (const t of allTasks) {
  if (!tasksBySprint[t.sprintId]) tasksBySprint[t.sprintId] = [];
  tasksBySprint[t.sprintId].push(t);
}

// Sprints to process
const targetSprints = SPRINT_ARG
  ? allSprints.filter(s => s.sprintId === SPRINT_ARG || s.sprintId.endsWith(`-${SPRINT_ARG}`))
  : allSprints;

if (SPRINT_ARG && targetSprints.length === 0) {
  console.error(`Error: sprint '${SPRINT_ARG}' not found in store`);
  process.exit(1);
}

// --- Generate MASTER_INDEX.md ---
{
  const masterPath = path.join(engRoot, 'MASTER_INDEX.md');
  let preserved = {};

  // Extract preserved sections (## headings not in GENERATED marker block)
  if (fs.existsSync(masterPath)) {
    const existing = fs.readFileSync(masterPath, 'utf8');
    const isGenerated = existing.trimStart().startsWith(GENERATED.trim().slice(0, 10));
    if (!isGenerated) {
      // Preserve all sections from manually written file
      const sections = existing.split(/^(?=## )/m);
      for (const s of sections) {
        const m = s.match(/^## (.+)/);
        if (m) preserved[m[1].trim()] = s;
      }
    }
  }

  const lines = [GENERATED, '', `# ${projectName} — Master Index`, '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`, ''];

  // Feature Registry
  lines.push('## Feature Registry', '');
  if (allFeatures.length > 0) {
    lines.push(`[Browse all ${allFeatures.length} features ↗](features/INDEX.md)`, '');
  } else {
    lines.push(`_[No features yet ↗](features/INDEX.md)_`, '');
  }

  // Sprint registry
  lines.push('## Sprint Registry', '');
  if (allSprints.length > 0) {
    const rows = [['Sprint', 'Title', 'Status', 'Tasks']];
    for (const s of [...allSprints].reverse()) {
      const tasks = tasksBySprint[s.sprintId] || [];
      const completed = tasks.filter(t => t.status === 'committed').length;
      rows.push([
        s.sprintId, s.title || '—', statusBadge(s.status),
        `${completed}/${tasks.length}`,
      ]);
    }
    lines.push(padTable(rows), '');
  } else {
    lines.push('_No sprints yet._', '');
  }

  // Task registry — most recent sprint first
  lines.push('## Task Registry', '');
  for (const sprint of [...allSprints].reverse()) {
    const tasks = (tasksBySprint[sprint.sprintId] || []).sort((a, b) => a.taskId.localeCompare(b.taskId));
    if (tasks.length === 0) continue;
    lines.push(`### ${sprint.sprintId}`, '');
    const rows = [['Task', 'Title', 'Status', 'Estimate']];
    const sprintDir = resolveDir(path.join(engRoot, 'sprints'), sprint.sprintId, sprint.sprintId.split('-').pop());
    for (const t of tasks) {
      // Derive task link from t.path if available (most reliable — already has correct dir names).
      // Fall back to filesystem detection against full task ID vs. trailing segment.
      let taskLink;
      if (t.path) {
        const rel = path.relative(engPath, t.path).replace(/\\/g, '/');
        taskLink = path.dirname(rel).replace(/\\/g, '/') + '/INDEX.md';
      } else {
        const taskDir = resolveDir(path.join(engRoot, 'sprints', sprintDir), t.taskId, t.taskId.split('-').pop());
        taskLink = `sprints/${sprintDir}/${taskDir}/INDEX.md`;
      }
      rows.push([
        `[${t.taskId}](${taskLink})`,
        t.title || '—', statusBadge(t.status), t.estimate || '—',
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // Bug registry
  if (allBugs.length > 0) {
    lines.push('## Bug Registry', '');
    const open   = allBugs.filter(b => !['fixed', 'verified'].includes(b.status));
    const closed = allBugs.filter(b =>  ['fixed', 'verified'].includes(b.status));
    const rows = [['Bug', 'Title', 'Severity', 'Status']];
    for (const b of [...open, ...closed]) {
      const bugDir = resolveDir(path.join(engRoot, 'bugs'), b.bugId, b.bugId.split('-').pop());
      rows.push([
        `[${b.bugId}](bugs/${bugDir}/INDEX.md)`,
        b.title || '—', b.severity || '—', statusBadge(b.status),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // Re-append preserved sections not already present
  for (const [heading, content] of Object.entries(preserved)) {
    if (!['Feature Registry', 'Sprint Registry', 'Task Registry', 'Bug Registry'].includes(heading)) {
      lines.push(content);
    }
  }

  writeFile(masterPath, lines.join('\n') + '\n');
}

// --- Generate features/INDEX.md and per-feature pages ---
{
  const featRoot = path.join(engRoot, 'features');

  const featLines = [GENERATED, '', `# Feature Registry`, '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`, ''];

  if (allFeatures.length > 0) {
    const rows = [['Feature ID', 'Title', 'Status', 'Sprints', 'Tasks']];
    for (const f of allFeatures) {
      if (!f.id) continue;
      const sp = f.sprints || [];
      const ts = f.tasks || [];
      rows.push([
        `[${f.id}](${f.id}.md)`,
        f.title || '—',
        statusBadge(f.status || 'draft'),
        sp.length ? sp.join(', ') : '—',
        ts.length ? ts.join(', ') : '—'
      ]);

      // Per-feature page
      const pfLines = [GENERATED, '', `# Feature: ${f.title || f.id}`, '',
        `> Feature ID: ${f.id}`,
        `> Status: ${statusBadge(f.status || 'draft')}`,
        `> Created: ${f.created_at || '—'}`,
        ''];
      
      if (f.description) pfLines.push('## Description', '', f.description, '');

      if (f.requirements && f.requirements.length > 0) {
        pfLines.push('## Requirements', '');
        f.requirements.forEach(req => pfLines.push(`- ${req}`));
        pfLines.push('');
      }

      if (sp.length > 0) {
        pfLines.push('## Linked Sprints', '');
        sp.forEach(s => pfLines.push(`- ${s}`));
        pfLines.push('');
      }

      if (ts.length > 0) {
        pfLines.push('## Linked Tasks', '');
        ts.forEach(t => pfLines.push(`- ${t}`));
        pfLines.push('');
      }

      writeFile(path.join(featRoot, `${f.id}.md`), pfLines.join('\n') + '\n');
    }
    featLines.push(padTable(rows), '');
  } else {
    featLines.push('_No features yet._', '');
  }

  writeFile(path.join(featRoot, 'INDEX.md'), featLines.join('\n') + '\n');
}

// --- Load events per sprint ---
function loadSprintEvents(sprintId) {
  return store.listEvents(sprintId).map(ev => {
    // Backfill attribution from filename when absent in JSON
    // Note: store.listEvents returns objects, but we might need the filename if it's missing
    // However, the FSImpl.listEvents just maps _readJson, which loses the filename.
    // To maintain the a-priori filename-based backfill, we need the filename.
    // Let's check if the store facade can provide it or if we should modify it.
    return ev;
  }).filter(Boolean);
}

// --- Format helpers ---
function fmtTokens(n) {
  if (n === undefined || n === null) return '—';
  return n.toLocaleString('en-US');
}

function fmtCost(n) {
  if (n === undefined || n === null) return '—';
  return `$${n.toFixed(4)}`;
}

function sourceLabel(sources) {
  // sources: Set of tokenSource values (may include undefined)
  const vals = [...sources];
  const hasReported  = vals.includes('reported');
  const hasEstimated = vals.includes('estimated');
  const hasUnknown   = vals.some(v => v === undefined || v === null);

  if (hasReported && !hasEstimated && !hasUnknown) return '(reported)';
  if (hasEstimated && !hasReported && !hasUnknown) return '(estimated)';
  if (!hasReported && !hasEstimated && hasUnknown)  return '(unknown)';
  return '(mixed)';
}

// --- Generate COST_REPORT.md per sprint ---
const REVIEW_PHASES = new Set(['review', 'review-plan', 'review-code', 'review-implementation']);
let costReportsWritten = 0;

for (const sprint of targetSprints) {
  const events = loadSprintEvents(sprint.sprintId);
  // Only events that have at least inputTokens present
  const tokenEvents = events.filter(e => e.inputTokens !== undefined);

  let sprintDirName;
  if (sprint.path) {
    sprintDirName = path.basename(sprint.path.replace(/\/$/, ''));
  } else {
    sprintDirName = resolveDir(
      path.join(engRoot, 'sprints'),
      sprint.sprintId,
      sprint.sprintId.split('-').pop()
    );
  }
  const reportPath = path.join(engRoot, 'sprints', sprintDirName, 'COST_REPORT.md');

  const lines = [
    GENERATED,
    '',
    `# Cost Report — ${sprint.sprintId}`,
    '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`,
    `> Sprint: ${sprint.title || sprint.sprintId}`,
    '',
  ];

  if (tokenEvents.length === 0) {
    lines.push('_No token data available for this sprint._', '');
    writeFile(reportPath, lines.join('\n') + '\n');
    costReportsWritten++;
    continue;
  }

  // --- Section 1: Per-task totals ---
  lines.push('## Per-Task Totals', '');
  {
    const byTask = {};
    for (const e of tokenEvents) {
      const tid = e.taskId || '(unknown)';
      if (!byTask[tid]) byTask[tid] = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, estimatedCostUSD: 0, sources: new Set() };
      const g = byTask[tid];
      g.inputTokens     += e.inputTokens     || 0;
      g.outputTokens    += e.outputTokens    || 0;
      g.cacheReadTokens += e.cacheReadTokens  || 0;
      g.cacheWriteTokens+= e.cacheWriteTokens || 0;
      g.estimatedCostUSD+= e.estimatedCostUSD || 0;
      g.sources.add(e.tokenSource);
    }
    const rows = [['Task', 'Input Tokens', 'Output Tokens', 'Cache Read', 'Cache Write', 'Est. Cost USD', 'Source']];
    for (const [tid, g] of Object.entries(byTask).sort(([a], [b]) => a.localeCompare(b))) {
      rows.push([
        tid,
        fmtTokens(g.inputTokens),
        fmtTokens(g.outputTokens),
        fmtTokens(g.cacheReadTokens),
        fmtTokens(g.cacheWriteTokens),
        fmtCost(g.estimatedCostUSD),
        sourceLabel(g.sources),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // --- Section 2: Per-role breakdown ---
  lines.push('## Per-Role Breakdown', '');
  {
    const byRole = {};
    for (const e of tokenEvents) {
      const role = e.role || '(unknown)';
      if (!byRole[role]) byRole[role] = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, estimatedCostUSD: 0 };
      const g = byRole[role];
      g.inputTokens     += e.inputTokens     || 0;
      g.outputTokens    += e.outputTokens    || 0;
      g.cacheReadTokens += e.cacheReadTokens  || 0;
      g.cacheWriteTokens+= e.cacheWriteTokens || 0;
      g.estimatedCostUSD+= e.estimatedCostUSD || 0;
    }
    const rows = [['Role', 'Input Tokens', 'Output Tokens', 'Cache Read', 'Cache Write', 'Est. Cost USD']];
    for (const [role, g] of Object.entries(byRole).sort(([a], [b]) => a.localeCompare(b))) {
      rows.push([
        role,
        fmtTokens(g.inputTokens),
        fmtTokens(g.outputTokens),
        fmtTokens(g.cacheReadTokens),
        fmtTokens(g.cacheWriteTokens),
        fmtCost(g.estimatedCostUSD),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // --- Section 3: Revision waste ---
  lines.push('## Revision Waste', '');
  {
    const revisionEvents = tokenEvents.filter(e => (e.iteration || 1) > 1 && REVIEW_PHASES.has(e.phase));
    if (revisionEvents.length === 0) {
      lines.push('_No revision waste in this sprint._', '');
    } else {
      const byTask = {};
      for (const e of revisionEvents) {
        const tid = e.taskId || '(unknown)';
        if (!byTask[tid]) byTask[tid] = { iterations: new Set(), inputTokens: 0, outputTokens: 0, estimatedCostUSD: 0 };
        const g = byTask[tid];
        g.iterations.add(e.iteration);
        g.inputTokens     += e.inputTokens     || 0;
        g.outputTokens    += e.outputTokens    || 0;
        g.estimatedCostUSD+= e.estimatedCostUSD || 0;
      }
      const rows = [['Task', 'Revision Iterations', 'Input Tokens', 'Output Tokens', 'Est. Cost USD']];
      for (const [tid, g] of Object.entries(byTask).sort(([a], [b]) => a.localeCompare(b))) {
        rows.push([
          tid,
          g.iterations.size,
          fmtTokens(g.inputTokens),
          fmtTokens(g.outputTokens),
          fmtCost(g.estimatedCostUSD),
        ]);
      }
      lines.push(padTable(rows), '');
    }
  }

  // --- Section 4: Model split ---
  lines.push('## Model Split', '');
  {
    const byModel = {};
    for (const e of tokenEvents) {
      const model = e.model || '(unknown)';
      if (!byModel[model]) byModel[model] = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, estimatedCostUSD: 0 };
      const g = byModel[model];
      g.inputTokens     += e.inputTokens     || 0;
      g.outputTokens    += e.outputTokens    || 0;
      g.cacheReadTokens += e.cacheReadTokens  || 0;
      g.cacheWriteTokens+= e.cacheWriteTokens || 0;
      g.estimatedCostUSD+= e.estimatedCostUSD || 0;
    }
    const rows = [['Model', 'Input Tokens', 'Output Tokens', 'Cache Read', 'Cache Write', 'Est. Cost USD']];
    for (const [model, g] of Object.entries(byModel).sort(([a], [b]) => a.localeCompare(b))) {
      rows.push([
        model,
        fmtTokens(g.inputTokens),
        fmtTokens(g.outputTokens),
        fmtTokens(g.cacheReadTokens),
        fmtTokens(g.cacheWriteTokens),
        fmtCost(g.estimatedCostUSD),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  writeFile(reportPath, lines.join('\n') + '\n');
  costReportsWritten++;
}

// --- Write COLLATION_STATE.json ---
const stateData = {
  collatedAt: new Date().toISOString(),
  featureCount: allFeatures.length,
  sprintCount: targetSprints.length,
  taskCount: allTasks.filter(t => targetSprints.some(s => s.sprintId === t.sprintId)).length,
  bugCount: allBugs.length,
};
writeFile(path.join(storeRoot, 'COLLATION_STATE.json'), JSON.stringify(stateData, null, 2) + '\n');

const tag = DRY_RUN ? '[dry-run] ' : '';
console.log(`${tag}Collated: ${targetSprints.length} sprint(s), ${allBugs.length} bug(s) → MASTER_INDEX.md updated, ${costReportsWritten} COST_REPORT(s) written`);
