#!/usr/bin/env node
'use strict';

// Forge tool: collate
// Regenerate markdown views from the JSON store. Deterministic — no AI needed.
// Usage: collate [SPRINT_ID] [--dry-run]

const fs = require('fs');
const path = require('path');

const DRY_RUN = process.argv.includes('--dry-run');
const SPRINT_ARG = process.argv.slice(2).find(a => !a.startsWith('--'));
const cwd = process.cwd();
const GENERATED = '<!-- GENERATED by forge/collate — do not edit manually -->';

// --- Helpers ---
function readConfig() {
  const p = path.join(cwd, '.forge', 'config.json');
  if (!fs.existsSync(p)) { console.error('Error: .forge/config.json not found'); process.exit(1); }
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch (e) {
    console.error(`Error: .forge/config.json is not valid JSON: ${e.message}`); process.exit(1);
  }
}

function readJson(p) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; }
}

function listJson(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.json')).map(f => readJson(path.join(dir, f))).filter(Boolean);
}

function writeFile(filePath, content) {
  if (DRY_RUN) { console.log(`[dry-run] would write: ${path.relative(cwd, filePath)}`); return; }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function fmtDuration(minutes) {
  if (minutes < 60) return `${Math.round(minutes)}m`;
  const h = Math.floor(minutes / 60), m = Math.round(minutes % 60);
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}

function fmtTs(iso) {
  if (!iso) return '—';
  return iso.replace('T', ' ').slice(0, 16);
}

function statusBadge(status) {
  const map = {
    committed: '✅', approved: '✅', implemented: '🔧', implementing: '🔧',
    'plan-approved': '📋', planned: '📋', draft: '📝',
    'plan-revision-required': '🔄', 'code-revision-required': '🔄',
    blocked: '🚫', escalated: '⚠️',
  };
  return map[status] || status;
}

function padTable(rows) {
  if (rows.length === 0) return '';
  const cols = rows[0].length;
  const widths = Array.from({ length: cols }, (_, i) => Math.max(...rows.map(r => String(r[i] ?? '').length)));
  return rows.map((r, ri) => {
    const cells = r.map((c, i) => String(c ?? '').padEnd(widths[i]));
    const line = `| ${cells.join(' | ')} |`;
    if (ri === 0) return line + '\n' + `| ${widths.map(w => '-'.repeat(w)).join(' | ')} |`;
    return line;
  }).join('\n');
}

// --- Load store ---
const config     = readConfig();
const storePath  = config.paths?.store || '.forge/store';
const engPath    = config.paths?.engineering || 'engineering';
const projectName = config.project?.name || config.project?.prefix || 'Project';

const storeRoot = path.join(cwd, storePath);
const engRoot   = path.join(cwd, engPath);

const allSprints = listJson(path.join(storeRoot, 'sprints'))
  .sort((a, b) => a.sprintId.localeCompare(b.sprintId));
const allTasks   = listJson(path.join(storeRoot, 'tasks'));
const allBugs    = listJson(path.join(storeRoot, 'bugs'));

// Group tasks by sprint
const tasksBySprint = {};
for (const t of allTasks) {
  if (!tasksBySprint[t.sprintId]) tasksBySprint[t.sprintId] = [];
  tasksBySprint[t.sprintId].push(t);
}

// Load events by sprint
function loadEvents(sprintId) {
  const evDir = path.join(storeRoot, 'events', sprintId);
  if (!fs.existsSync(evDir)) return [];
  return fs.readdirSync(evDir)
    .filter(f => f.endsWith('.json'))
    .map(f => readJson(path.join(evDir, f)))
    .filter(Boolean)
    .sort((a, b) => (a.startTimestamp || '').localeCompare(b.startTimestamp || ''));
}

// Sprints to process
const targetSprints = SPRINT_ARG
  ? allSprints.filter(s => s.sprintId === SPRINT_ARG || s.sprintId.endsWith(`-${SPRINT_ARG}`))
  : allSprints;

if (SPRINT_ARG && targetSprints.length === 0) {
  console.error(`Error: sprint '${SPRINT_ARG}' not found in store`);
  process.exit(1);
}

// --- Generate TIMESHEET.md per sprint ---
for (const sprint of targetSprints) {
  const events = loadEvents(sprint.sprintId);
  const tasks  = (tasksBySprint[sprint.sprintId] || [])
    .sort((a, b) => a.taskId.localeCompare(b.taskId));

  const lines = [GENERATED, '', `# ${sprint.sprintId} — Timesheet`, ''];

  // Sprint summary
  lines.push('## Summary', '');
  const summaryRows = [
    ['Sprint', 'Status', 'Tasks'],
    [sprint.sprintId, sprint.status, tasks.length],
  ];
  lines.push(padTable(summaryRows), '');

  // Task status table
  if (tasks.length > 0) {
    lines.push('## Tasks', '');
    const taskRows = [['Task ID', 'Title', 'Status', 'Estimate']];
    for (const t of tasks) {
      taskRows.push([t.taskId, t.title || '—', `${statusBadge(t.status)} ${t.status}`, t.estimate || '—']);
    }
    lines.push(padTable(taskRows), '');
  }

  // Activity log from events
  if (events.length > 0) {
    lines.push('## Activity Log', '');
    const evRows = [['Timestamp', 'Task', 'Role', 'Phase', 'Duration', 'Verdict']];
    let totalMinutes = 0;
    for (const e of events) {
      totalMinutes += e.durationMinutes || 0;
      evRows.push([
        fmtTs(e.startTimestamp),
        e.taskId || '—',
        e.role || '—',
        e.phase || '—',
        e.durationMinutes != null ? fmtDuration(e.durationMinutes) : '—',
        e.verdict || '—',
      ]);
    }
    lines.push(padTable(evRows), '');
    if (totalMinutes > 0) lines.push(`**Total tracked:** ${fmtDuration(totalMinutes)}`, '');
  }

  const sprintDirName = sprint.sprintId.split('-').pop(); // e.g. S01
  const timesheetPath = path.join(engRoot, 'sprints', sprintDirName, 'TIMESHEET.md');
  writeFile(timesheetPath, lines.join('\n') + '\n');
}

// --- Generate bugs/TIMESHEET.md ---
if (allBugs.length > 0) {
  const lines = [GENERATED, '', '# Bug Registry — Timesheet', ''];
  const open   = allBugs.filter(b => !['fixed', 'verified'].includes(b.status));
  const closed = allBugs.filter(b =>  ['fixed', 'verified'].includes(b.status));

  function bugTable(bugs, heading) {
    if (bugs.length === 0) return;
    lines.push(`## ${heading}`, '');
    const rows = [['Bug ID', 'Title', 'Severity', 'Status', 'Reported']];
    for (const b of bugs) {
      rows.push([b.bugId, b.title || '—', b.severity || '—', b.status, fmtTs(b.reportedAt)]);
    }
    lines.push(padTable(rows), '');
  }

  bugTable(open, 'Open');
  bugTable(closed, 'Resolved');

  writeFile(path.join(engRoot, 'bugs', 'TIMESHEET.md'), lines.join('\n') + '\n');
}

// --- Generate MASTER_INDEX.md ---
{
  const masterPath = path.join(engRoot, 'MASTER_INDEX.md');
  let preserved = {};

  // Extract preserved sections (## headings not in GENERATED marker block)
  if (fs.existsSync(masterPath)) {
    const existing = fs.readFileSync(masterPath, 'utf8');
    const isGenerated = existing.trimStart().startsWith(GENERATED.trim().slice(0, 10));
    if (!isGenerated) {
      // Preserve all sections from manually written file
      const sections = existing.split(/^(?=## )/m);
      for (const s of sections) {
        const m = s.match(/^## (.+)/);
        if (m) preserved[m[1].trim()] = s;
      }
    }
  }

  const lines = [GENERATED, '', `# ${projectName} — Master Index`, '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`, ''];

  // Sprint registry
  lines.push('## Sprint Registry', '');
  if (allSprints.length > 0) {
    const rows = [['Sprint', 'Title', 'Status', 'Tasks', 'Timesheet']];
    for (const s of [...allSprints].reverse()) {
      const tasks = tasksBySprint[s.sprintId] || [];
      const completed = tasks.filter(t => t.status === 'committed').length;
      const sprintDir = s.sprintId.split('-').pop();
      rows.push([
        s.sprintId, s.title || '—', `${statusBadge(s.status)} ${s.status}`,
        `${completed}/${tasks.length}`,
        `[TIMESHEET](sprints/${sprintDir}/TIMESHEET.md)`,
      ]);
    }
    lines.push(padTable(rows), '');
  } else {
    lines.push('_No sprints yet._', '');
  }

  // Task registry — most recent sprint first
  lines.push('## Task Registry', '');
  for (const sprint of [...allSprints].reverse()) {
    const tasks = (tasksBySprint[sprint.sprintId] || []).sort((a, b) => a.taskId.localeCompare(b.taskId));
    if (tasks.length === 0) continue;
    lines.push(`### ${sprint.sprintId}`, '');
    const rows = [['Task', 'Title', 'Status', 'Estimate']];
    for (const t of tasks) {
      const taskDir = t.taskId.split('-').pop();
      const sprintDir = sprint.sprintId.split('-').pop();
      rows.push([
        `[${t.taskId}](sprints/${sprintDir}/${taskDir}/INDEX.md)`,
        t.title || '—', `${statusBadge(t.status)} ${t.status}`, t.estimate || '—',
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // Bug registry
  if (allBugs.length > 0) {
    lines.push('## Bug Registry', '');
    const open   = allBugs.filter(b => !['fixed', 'verified'].includes(b.status));
    const closed = allBugs.filter(b =>  ['fixed', 'verified'].includes(b.status));
    const rows = [['Bug', 'Title', 'Severity', 'Status']];
    for (const b of [...open, ...closed]) {
      const bugDir = b.bugId.split('-').pop();
      rows.push([
        `[${b.bugId}](bugs/${bugDir}/INDEX.md)`,
        b.title || '—', b.severity || '—', `${statusBadge(b.status)} ${b.status}`,
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // Re-append preserved sections not already present
  for (const [heading, content] of Object.entries(preserved)) {
    if (!['Sprint Registry', 'Task Registry', 'Bug Registry'].includes(heading)) {
      lines.push(content);
    }
  }

  writeFile(masterPath, lines.join('\n') + '\n');
}

// --- Write COLLATION_STATE.json ---
const stateData = {
  collatedAt: new Date().toISOString(),
  sprintCount: targetSprints.length,
  taskCount: allTasks.filter(t => targetSprints.some(s => s.sprintId === t.sprintId)).length,
  bugCount: allBugs.length,
};
writeFile(path.join(storeRoot, 'COLLATION_STATE.json'), JSON.stringify(stateData, null, 2) + '\n');

const tag = DRY_RUN ? '[dry-run] ' : '';
console.log(`${tag}Collated: ${targetSprints.length} sprint(s), ${allBugs.length} bug(s) → MASTER_INDEX.md updated`);
