#!/usr/bin/env node
'use strict';

// Forge tool: collate
// Regenerate markdown views from the JSON store. Deterministic — no AI needed.
// Usage: collate [SPRINT_ID | BUG_ID] [--dry-run] [--purge-events]
//
// Positional argument can be a sprint ID (e.g. FORGE-S12) or a bug ID
// (e.g. FORGE-BUG-007, HELLO-B02). Bug IDs are first-class arguments:
// passing a bug ID automatically enables event purging for that entity,
// so `collate HELLO-B02` works identically to `collate HELLO-B02 --purge-events`.
//
// --purge-events  After generating COST_REPORT.md for the given SPRINT_ID,
//                 delete .forge/store/events/{SPRINT_ID}/ entirely.
//                 If SPRINT_ID is not a known sprint (e.g. a bug ID), no
//                 COST_REPORT is generated but the event directory is still
//                 purged. Requires a positional argument. Safe to combine with
//                 --dry-run (reports what would be deleted without deleting).

const fs = require('fs');
const path = require('path');
const { ok: resultOk, fail: resultFail, RESULT_CODES } = require('./lib/result.js');

let _store;
function _getStore() { return _store || (_store = require('./store.cjs')); }

const GENERATED = '<!-- GENERATED by forge/collate — do not edit manually -->';

// --- Pure helpers (exported for testing) ---

function statusBadge(status) {
  const map = {
    committed: '✅', approved: '✅', completed: '✅',
    'retrospective-done': '✅', fixed: '✅', verified: '✅',
    implemented: '🔧', implementing: '🔧',
    'in-progress': '🔵', active: '🔵',
    'plan-approved': '📋', 'review-approved': '📋', planned: '📋',
    planning: '📝', draft: '📝',
    triaged: '🟡', 'partially-completed': '🟡',
    'plan-revision-required': '🔄', 'code-revision-required': '🔄',
    reported: '🔴', blocked: '🚫', escalated: '⚠️',
    abandoned: '❌',
  };
  const badge = map[status];
  return badge ? `${badge} ${status}` : status;
}

function padTable(rows) {
  if (rows.length === 0) return '';
  const cols = rows[0].length;
  const widths = Array.from({ length: cols }, (_, i) => Math.max(...rows.map(r => String(r[i] ?? '').length)));
  return rows.map((r, ri) => {
    const cells = r.map((c, i) => String(c ?? '').padEnd(widths[i]));
    const line = `| ${cells.join(' | ')} |`;
    if (ri === 0) return line + '\n' + `| ${widths.map(w => '-'.repeat(w)).join(' | ')} |`;
    return line;
  }).join('\n');
}

function fmtTokens(n) {
  if (n === undefined || n === null) return '—';
  return n.toLocaleString('en-US');
}

function fmtCost(n) {
  if (n === undefined || n === null) return '—';
  return `$${n.toFixed(4)}`;
}

function sourceLabel(sources) {
  // sources: Set of tokenSource values (may include undefined)
  const vals = [...sources];
  const hasReported  = vals.includes('reported');
  const hasEstimated = vals.includes('estimated');
  const hasUnknown   = vals.some(v => v === undefined || v === null);

  if (hasReported && !hasEstimated && !hasUnknown) return '(reported)';
  if (hasEstimated && !hasReported && !hasUnknown) return '(estimated)';
  if (!hasReported && !hasEstimated && hasUnknown)  return '(unknown)';
  return '(mixed)';
}

const SPRINT_DOCS = [
  { file: 'SPRINT_PLAN.md',         label: 'Sprint Plan',         purpose: 'Sprint scope and task definitions' },
  { file: 'SPRINT_REQUIREMENTS.md', label: 'Sprint Requirements', purpose: 'Requirements and acceptance criteria' },
  { file: 'COST_REPORT.md',         label: 'Cost Report',         purpose: 'Token usage and cost analysis' },
];

const TASK_DOCS = [
  { file: 'TASK_PROMPT.md',         label: 'Task Prompt',         purpose: 'Task definition and prompt' },
  { file: 'PLAN.md',                label: 'Plan',                purpose: 'Implementation plan' },
  { file: 'PROGRESS.md',            label: 'Progress',            purpose: 'Implementation progress log' },
  { file: 'ARCHITECT_APPROVAL.md',  label: 'Architect Approval',  purpose: 'Architecture review' },
  { file: 'CODE_REVIEW.md',         label: 'Code Review',         purpose: 'Code review' },
  { file: 'VALIDATION_REPORT.md',   label: 'Validation Report',   purpose: 'Validation results' },
];

// Resolve the task directory name within a sprint directory.
// Returns the directory name string, or null if no directory can be found.
//
// Resolution order:
// 1. If task.path is under engPath (an engineering KB path) — basename of that path.
// 2. Filesystem scan of sprintDirPath for a directory whose name starts with taskId
//    or whose leading integer matches that of taskId (slug-named dirs).
// 3. null if nothing matches.
function resolveTaskDir(task, sprintDirPath, engPath) {
  const normalizedTaskPath = task.path ? task.path.replace(/\\/g, '/').replace(/\/$/, '') : null;
  const normalizedEngPath  = engPath   ? engPath.replace(/\\/g, '/').replace(/\/$/, '')  : '';

  // Case 1: path is under the engineering root — it IS the task directory
  if (normalizedTaskPath && normalizedEngPath && normalizedTaskPath.startsWith(normalizedEngPath + '/')) {
    return resultOk(path.basename(normalizedTaskPath));
  }

  // Case 2 (and fallback for case 1 missing): filesystem scan
  if (fs.existsSync(sprintDirPath)) {
    const entries = fs.readdirSync(sprintDirPath).sort();
    // Prefer exact match first
    if (entries.includes(task.taskId)) return resultOk(task.taskId);
    // Then prefix match (slug-named dirs like TST-S01-T01-my-feature)
    const prefix = task.taskId + '-';
    const slugMatch = entries.find(e => e.startsWith(prefix) && fs.statSync(path.join(sprintDirPath, e)).isDirectory());
    if (slugMatch) return resultOk(slugMatch);
    // Numeric fallback: match first integer in taskId
    const numMatch = task.taskId.match(/\d+/g);
    const targetNum = numMatch ? parseInt(numMatch[numMatch.length - 1], 10) : null;
    if (targetNum !== null) {
      for (const e of entries) {
        const em = e.match(/\d+/g);
        if (em && parseInt(em[em.length - 1], 10) === targetNum && fs.statSync(path.join(sprintDirPath, e)).isDirectory()) {
          return resultOk(e);
        }
      }
    }
  }

  return resultFail(RESULT_CODES.MISSING_DIR, `No task directory found for ${task.taskId} in ${sprintDirPath}`);
}

function buildSprintIndex(sprint, tasks, availableDocs) {
  const avail = new Set(availableDocs);
  const lines = [GENERATED, '', `# Sprint: ${sprint.title || sprint.sprintId}`, '',
    `> Sprint ID: ${sprint.sprintId}`,
    `> Status: ${statusBadge(sprint.status)}`,
    sprint.executionMode ? `> Execution Mode: ${sprint.executionMode}` : null,
    ''].filter(l => l !== null);

  if (sprint.goal) lines.push('## Goal', '', sprint.goal, '');
  if (sprint.description && sprint.description !== sprint.goal) lines.push('## Description', '', sprint.description, '');

  const presentDocs = SPRINT_DOCS.filter(d => avail.has(d.file));
  if (presentDocs.length > 0) {
    lines.push('## Sprint Documents', '');
    const rows = [['Document', 'Purpose']];
    for (const d of presentDocs) rows.push([`[${d.label}](${d.file})`, d.purpose]);
    lines.push(padTable(rows), '');
  }

  lines.push('## Tasks', '');
  if (tasks.length > 0) {
    const rows = [['Task', 'Title', 'Status', 'Estimate']];
    for (const t of tasks) {
      const linkDir = t._taskDir || t.taskId;
      rows.push([`[${t.taskId}](${linkDir}/INDEX.md)`, t.title || '—', statusBadge(t.status), t.estimate || '—']);
    }
    lines.push(padTable(rows), '');
  } else {
    lines.push('_No tasks._', '');
  }

  return lines.join('\n') + '\n';
}

function buildTaskIndex(task, availableDocs) {
  const avail = new Set(availableDocs);
  const lines = [GENERATED, '', `# Task: ${task.title || task.taskId}`, '',
    `> Task ID: ${task.taskId}`,
    `> Sprint: [${task.sprintId}](../INDEX.md)`,
    `> Status: ${statusBadge(task.status)}`,
    task.estimate ? `> Estimate: ${task.estimate}` : null,
    ''].filter(l => l !== null);

  if (task.description) lines.push('## Description', '', task.description, '');

  const presentDocs = TASK_DOCS.filter(d => avail.has(d.file));
  if (presentDocs.length > 0) {
    lines.push('## Task Documents', '');
    const rows = [['Document', 'Purpose']];
    for (const d of presentDocs) rows.push([`[${d.label}](${d.file})`, d.purpose]);
    lines.push(padTable(rows), '');
  }

  return lines.join('\n') + '\n';
}

const BUG_DOCS = [
  { file: 'ANALYSIS.md',         label: 'Analysis',          purpose: 'Bug analysis and triage' },
  { file: 'BUG_FIX_PLAN.md',    label: 'Fix Plan',           purpose: 'Fix implementation plan' },
  { file: 'PLAN.md',             label: 'Plan',               purpose: 'Fix implementation plan' },
  { file: 'PLAN_REVIEW.md',      label: 'Plan Review',        purpose: 'Fix plan review' },
  { file: 'PROGRESS.md',         label: 'Progress',           purpose: 'Fix progress log' },
  { file: 'APPROVAL.md',         label: 'Approval',           purpose: 'Architecture approval' },
  { file: 'ARCHITECT_APPROVAL.md', label: 'Architect Approval', purpose: 'Architecture approval' },
  { file: 'CODE_REVIEW.md',      label: 'Code Review',        purpose: 'Code review' },
  { file: 'VALIDATION_REPORT.md', label: 'Validation Report', purpose: 'Fix validation' },
];

function buildBugIndex(bug, availableDocs) {
  const avail = new Set(availableDocs);
  const lines = [GENERATED, '', `# Bug: ${bug.title || bug.bugId}`, '',
    `> Bug ID: ${bug.bugId}`,
    `> Severity: ${bug.severity || '—'}`,
    `> Status: ${statusBadge(bug.status)}`,
    bug.reportedAt ? `> Reported: ${bug.reportedAt.slice(0, 10)}` : null,
    bug.resolvedAt ? `> Resolved: ${bug.resolvedAt.slice(0, 10)}` : null,
    ''].filter(l => l !== null);

  if (bug.description) lines.push('## Description', '', bug.description, '');

  const presentDocs = BUG_DOCS.filter(d => avail.has(d.file));
  if (presentDocs.length > 0) {
    lines.push('## Bug Documents', '');
    const rows = [['Document', 'Purpose']];
    for (const d of presentDocs) rows.push([`[${d.label}](${d.file})`, d.purpose]);
    lines.push(padTable(rows), '');
  }

  return lines.join('\n') + '\n';
}

/**
 * Detect whether a string matches the bug-ID pattern.
 * Bug IDs match one of these patterns:
 * 1. Contains 'BUG-' followed by digits (e.g., BUG-001, FORGE-BUG-007)
 * 2. Contains '-B' followed by digits at a segment boundary (e.g., HELLO-B02)
 * Sprint IDs (FORGE-S12) and task IDs (FORGE-S12-T03) are excluded.
 */
function isBugId(id) {
  if (!id || typeof id !== 'string') return false;
  return /BUG-\d+/.test(id) || /-B\d+\b/.test(id);
}

module.exports = { statusBadge, padTable, fmtTokens, fmtCost, sourceLabel, GENERATED, buildSprintIndex, buildTaskIndex, buildBugIndex, resolveTaskDir, isBugId };

// --- CLI ---
if (require.main === module) {

const DRY_RUN = process.argv.includes('--dry-run');
const SPRINT_ARG = process.argv.slice(2).find(a => !a.startsWith('--'));

// Bug IDs are first-class arguments — auto-enable purge when a bug ID is passed.
// This makes `collate.cjs HELLO-B02` work identically to `collate.cjs HELLO-B02 --purge-events`.
const IS_BUG_ARG = isBugId(SPRINT_ARG);
const PURGE_EVENTS = process.argv.includes('--purge-events') || IS_BUG_ARG;

if (PURGE_EVENTS && !SPRINT_ARG) {
  console.error('Error: --purge-events requires a sprint or bug ID argument');
  process.exit(1);
}
const cwd = process.cwd();

function writeFile(filePath, content) {
  if (DRY_RUN) { console.log(`[dry-run] would write: ${path.relative(cwd, filePath)}`); return; }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

// Resolve a directory name under `base` by trying candidates in order.
// Returns the first candidate whose directory exists. If none exist,
// attempts a numeric glob: finds the first alphabetically-sorted dir
// in `base` whose first integer matches the first integer in the last
// candidate. Falls back to the last candidate if no match is found.
function resolveDir(base, ...candidates) {
  for (const c of candidates) {
    if (fs.existsSync(path.join(base, c))) return c;
  }
  // Numeric glob fallback
  const last = candidates[candidates.length - 1];
  const numMatch = last.match(/\d+/);
  if (numMatch && fs.existsSync(base)) {
    const target = parseInt(numMatch[0], 10);
    const dirs = fs.readdirSync(base).sort();
    for (const d of dirs) {
      const m = d.match(/\d+/);
      if (m && parseInt(m[0], 10) === target) return d;
    }
  }
  return last;
}

// --- Load store ---
function readConfig() {
  const p = path.join(cwd, '.forge', 'config.json');
  if (!fs.existsSync(p)) { console.error('Error: .forge/config.json not found'); process.exit(1); }
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch (e) {
    console.error(`Error: .forge/config.json is not valid JSON: ${e.message}`); process.exit(1);
  }
}

const config = readConfig();
const storePath  = config.paths?.store || '.forge/store';
const engPath    = config.paths?.engineering || 'engineering';
const projectName = config.project?.name || config.project?.prefix || 'Project';

const storeRoot = path.join(cwd, storePath);
const engRoot   = path.join(cwd, engPath);

const store = _getStore();
const allSprints = store.listSprints()
  .sort((a, b) => a.sprintId.localeCompare(b.sprintId));
const allTasks   = store.listTasks();
const allBugs    = store.listBugs();
const allFeatures= store.listFeatures()
  .sort((a, b) => (a.id || '').localeCompare(b.id || ''));

// Group tasks by sprint
const tasksBySprint = {};
for (const t of allTasks) {
  if (!tasksBySprint[t.sprintId]) tasksBySprint[t.sprintId] = [];
  tasksBySprint[t.sprintId].push(t);
}

// Sprints to process
const targetSprints = SPRINT_ARG
  ? allSprints.filter(s => s.sprintId === SPRINT_ARG || s.sprintId.endsWith(`-${SPRINT_ARG}`))
  : allSprints;

if (SPRINT_ARG && targetSprints.length === 0) {
  if (IS_BUG_ARG || PURGE_EVENTS) {
    // Bug ID or non-sprint entity with --purge-events — skip sprint processing,
    // fall through to bug INDEX generation and purge step.
  } else {
    console.error(`Error: '${SPRINT_ARG}' not found as a sprint or bug in store`);
    process.exit(1);
  }
}

// --- Generate MASTER_INDEX.md ---
{
  const masterPath = path.join(engRoot, 'MASTER_INDEX.md');
  let preserved = {};

  // Extract preserved sections (## headings not in GENERATED marker block)
  if (fs.existsSync(masterPath)) {
    const existing = fs.readFileSync(masterPath, 'utf8');
    const isGenerated = existing.trimStart().startsWith(GENERATED.trim().slice(0, 10));
    if (!isGenerated) {
      // Preserve all sections from manually written file
      const sections = existing.split(/^(?=## )/m);
      for (const s of sections) {
        const m = s.match(/^## (.+)/);
        if (m) preserved[m[1].trim()] = s;
      }
    }
  }

  const lines = [GENERATED, '', `# ${projectName} — Master Index`, '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`, ''];

  // Feature Registry
  lines.push('## Feature Registry', '');
  if (allFeatures.length > 0) {
    lines.push(`[Browse all ${allFeatures.length} features ↗](features/INDEX.md)`, '');
  } else {
    lines.push(`_[No features yet ↗](features/INDEX.md)_`, '');
  }

  // Sprint registry
  lines.push('## Sprint Registry', '');
  if (allSprints.length > 0) {
    const rows = [['Sprint', 'Title', 'Status', 'Tasks']];
    for (const s of [...allSprints].reverse()) {
      const tasks = tasksBySprint[s.sprintId] || [];
      const completed = tasks.filter(t => t.status === 'committed').length;
      rows.push([
        s.sprintId, s.title || '—', statusBadge(s.status),
        `${completed}/${tasks.length}`,
      ]);
    }
    lines.push(padTable(rows), '');
  } else {
    lines.push('_No sprints yet._', '');
  }

  // Task registry — most recent sprint first
  lines.push('## Task Registry', '');
  for (const sprint of [...allSprints].reverse()) {
    const tasks = (tasksBySprint[sprint.sprintId] || []).sort((a, b) => a.taskId.localeCompare(b.taskId));
    if (tasks.length === 0) continue;
    lines.push(`### ${sprint.sprintId}`, '');
    const rows = [['Task', 'Title', 'Status', 'Estimate']];
    const sprintDir = sprint.path
      ? path.basename(sprint.path.replace(/\/$/, ''))
      : resolveDir(path.join(engRoot, 'sprints'), sprint.sprintId, sprint.sprintId.split('-').pop());
    for (const t of tasks) {
      // Derive task link from t.path if available (most reliable — already has correct dir names).
      // Fall back to filesystem detection against full task ID vs. trailing segment.
      let taskLink;
      if (t.path) {
        // If path is under the engineering root, it IS the task directory — link directly.
        // Otherwise (e.g. forge/tools/seed-store.cjs), it's a plugin source reference;
        // strip the filename to get the containing directory.
        const normalizedPath = t.path.replace(/\\/g, '/').replace(/\/$/, '');
        const normalizedEngPath = engPath.replace(/\\/g, '/').replace(/\/$/, '');
        if (normalizedPath.startsWith(normalizedEngPath + '/')) {
          const rel = path.relative(engPath, t.path).replace(/\\/g, '/');
          taskLink = rel + '/INDEX.md';
        } else {
          const rel = path.relative(engPath, t.path).replace(/\\/g, '/');
          taskLink = path.dirname(rel).replace(/\\/g, '/') + '/INDEX.md';
        }
      } else {
        const taskDir = resolveDir(path.join(engRoot, 'sprints', sprintDir), t.taskId, t.taskId.split('-').pop());
        taskLink = `sprints/${sprintDir}/${taskDir}/INDEX.md`;
      }
      rows.push([
        `[${t.taskId}](${taskLink})`,
        t.title || '—', statusBadge(t.status), t.estimate || '—',
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // Bug registry
  if (allBugs.length > 0) {
    lines.push('## Bug Registry', '');
    const open   = allBugs.filter(b => !['fixed', 'verified'].includes(b.status));
    const closed = allBugs.filter(b =>  ['fixed', 'verified'].includes(b.status));
    const rows = [['Bug', 'Title', 'Severity', 'Status']];
    for (const b of [...open, ...closed]) {
      const bugDir = resolveDir(path.join(engRoot, 'bugs'), b.bugId, b.bugId.split('-').pop());
      rows.push([
        `[${b.bugId}](bugs/${bugDir}/INDEX.md)`,
        b.title || '—', b.severity || '—', statusBadge(b.status),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // Re-append preserved sections not already present
  for (const [heading, content] of Object.entries(preserved)) {
    if (!['Feature Registry', 'Sprint Registry', 'Task Registry', 'Bug Registry'].includes(heading)) {
      lines.push(content);
    }
  }

  writeFile(masterPath, lines.join('\n') + '\n');
}

// --- Generate features/INDEX.md and per-feature pages ---
{
  const featRoot = path.join(engRoot, 'features');

  const featLines = [GENERATED, '', `# Feature Registry`, '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`, ''];

  if (allFeatures.length > 0) {
    const rows = [['Feature ID', 'Title', 'Status', 'Sprints', 'Tasks']];
    for (const f of allFeatures) {
      if (!f.id) continue;
      const sp = f.sprints || [];
      const ts = f.tasks || [];
      rows.push([
        `[${f.id}](${f.id}.md)`,
        f.title || '—',
        statusBadge(f.status || 'draft'),
        sp.length ? sp.join(', ') : '—',
        ts.length ? ts.join(', ') : '—'
      ]);

      // Per-feature page
      const pfLines = [GENERATED, '', `# Feature: ${f.title || f.id}`, '',
        `> Feature ID: ${f.id}`,
        `> Status: ${statusBadge(f.status || 'draft')}`,
        `> Created: ${f.created_at || '—'}`,
        ''];

      if (f.description) pfLines.push('## Description', '', f.description, '');

      if (f.requirements && f.requirements.length > 0) {
        pfLines.push('## Requirements', '');
        f.requirements.forEach(req => pfLines.push(`- ${req}`));
        pfLines.push('');
      }

      if (sp.length > 0) {
        pfLines.push('## Linked Sprints', '');
        sp.forEach(s => pfLines.push(`- ${s}`));
        pfLines.push('');
      }

      if (ts.length > 0) {
        pfLines.push('## Linked Tasks', '');
        ts.forEach(t => pfLines.push(`- ${t}`));
        pfLines.push('');
      }

      writeFile(path.join(featRoot, `${f.id}.md`), pfLines.join('\n') + '\n');
    }
    featLines.push(padTable(rows), '');
  } else {
    featLines.push('_No features yet._', '');
  }

  writeFile(path.join(featRoot, 'INDEX.md'), featLines.join('\n') + '\n');
}

// --- Load events per sprint ---
function loadSprintEvents(sprintId) {
  return _getStore().listEvents(sprintId).map(ev => {
    // Backfill attribution from filename when absent in JSON
    // Note: store.listEvents returns objects, but we might need the filename if it's missing
    // However, the FSImpl.listEvents just maps _readJson, which loses the filename.
    // To maintain the a-priori filename-based backfill, we need the filename.
    // Let's check if the store facade can provide it or if we should modify it.
    return ev;
  }).filter(Boolean);
}

// --- Generate Sprint INDEX.md and Task INDEX.md ---
function availableDocsIn(dir, knownDocs) {
  if (!fs.existsSync(dir)) return [];
  return knownDocs.map(d => d.file).filter(f => fs.existsSync(path.join(dir, f)));
}

let sprintIndexesWritten = 0;
let taskIndexesWritten = 0;

for (const sprint of targetSprints) {
  let sprintDirName;
  if (sprint.path) {
    sprintDirName = path.basename(sprint.path.replace(/\/$/, ''));
  } else {
    sprintDirName = resolveDir(
      path.join(engRoot, 'sprints'),
      sprint.sprintId,
      sprint.sprintId.split('-').pop()
    );
  }
  const sprintDir = path.join(engRoot, 'sprints', sprintDirName);

  // Resolve task directories for all tasks in this sprint
  const rawSprintTasks = (tasksBySprint[sprint.sprintId] || []).sort((a, b) => a.taskId.localeCompare(b.taskId));
  const sprintTasks = rawSprintTasks.map(t => {
    const dirResult = resolveTaskDir(t, sprintDir, engPath);
    return dirResult.ok ? Object.assign({}, t, { _taskDir: dirResult.value }) : t;
  });

  // Sprint INDEX.md — pass tasks with _taskDir so links resolve correctly
  const sprintAvailDocs = availableDocsIn(sprintDir, SPRINT_DOCS);
  writeFile(path.join(sprintDir, 'INDEX.md'), buildSprintIndex(sprint, sprintTasks, sprintAvailDocs));
  sprintIndexesWritten++;

  // Task INDEX.md files — generate for every task that has a KB directory
  for (const task of sprintTasks) {
    if (!task._taskDir) continue;
    const taskDir = path.join(sprintDir, task._taskDir);
    if (!fs.existsSync(taskDir)) continue;
    const taskAvailDocs = availableDocsIn(taskDir, TASK_DOCS);
    writeFile(path.join(taskDir, 'INDEX.md'), buildTaskIndex(task, taskAvailDocs));
    taskIndexesWritten++;
  }
}

// --- Generate Bug INDEX.md files ---
let bugIndexesWritten = 0;
for (const bug of allBugs) {
  const bugDirName = resolveDir(path.join(engRoot, 'bugs'), bug.bugId, bug.bugId.split('-').pop());
  const bugDir = path.join(engRoot, 'bugs', bugDirName);
  if (!fs.existsSync(bugDir)) continue;
  const bugAvailDocs = availableDocsIn(bugDir, BUG_DOCS);
  writeFile(path.join(bugDir, 'INDEX.md'), buildBugIndex(bug, bugAvailDocs));
  bugIndexesWritten++;
}

// --- Generate COST_REPORT.md per sprint ---
const REVIEW_PHASES = new Set(['review', 'review-plan', 'review-code', 'review-implementation']);
let costReportsWritten = 0;

for (const sprint of targetSprints) {
  const events = loadSprintEvents(sprint.sprintId);
  // Only events that have at least inputTokens present
  const tokenEvents = events.filter(e => e.inputTokens !== undefined);

  let sprintDirName;
  if (sprint.path) {
    sprintDirName = path.basename(sprint.path.replace(/\/$/, ''));
  } else {
    sprintDirName = resolveDir(
      path.join(engRoot, 'sprints'),
      sprint.sprintId,
      sprint.sprintId.split('-').pop()
    );
  }
  const reportPath = path.join(engRoot, 'sprints', sprintDirName, 'COST_REPORT.md');

  const lines = [
    GENERATED,
    '',
    `# Cost Report — ${sprint.sprintId}`,
    '',
    `> Generated: ${new Date().toISOString().slice(0, 10)}`,
    `> Sprint: ${sprint.title || sprint.sprintId}`,
    '',
  ];

  if (tokenEvents.length === 0) {
    lines.push('_No token data available for this sprint._', '');
    writeFile(reportPath, lines.join('\n') + '\n');
    costReportsWritten++;
    continue;
  }

  // --- Section 1: Per-task totals ---
  lines.push('## Per-Task Totals', '');
  {
    const byTask = {};
    for (const e of tokenEvents) {
      const tid = e.taskId || '(unknown)';
      if (!byTask[tid]) byTask[tid] = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, estimatedCostUSD: 0, sources: new Set() };
      const g = byTask[tid];
      g.inputTokens     += e.inputTokens     || 0;
      g.outputTokens    += e.outputTokens    || 0;
      g.cacheReadTokens += e.cacheReadTokens  || 0;
      g.cacheWriteTokens+= e.cacheWriteTokens || 0;
      g.estimatedCostUSD+= e.estimatedCostUSD || 0;
      g.sources.add(e.tokenSource);
    }
    const rows = [['Task', 'Input Tokens', 'Output Tokens', 'Cache Read', 'Cache Write', 'Est. Cost USD', 'Source']];
    for (const [tid, g] of Object.entries(byTask).sort(([a], [b]) => a.localeCompare(b))) {
      rows.push([
        tid,
        fmtTokens(g.inputTokens),
        fmtTokens(g.outputTokens),
        fmtTokens(g.cacheReadTokens),
        fmtTokens(g.cacheWriteTokens),
        fmtCost(g.estimatedCostUSD),
        sourceLabel(g.sources),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // --- Section 2: Per-role breakdown ---
  lines.push('## Per-Role Breakdown', '');
  {
    const byRole = {};
    for (const e of tokenEvents) {
      const role = e.role || '(unknown)';
      if (!byRole[role]) byRole[role] = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, estimatedCostUSD: 0 };
      const g = byRole[role];
      g.inputTokens     += e.inputTokens     || 0;
      g.outputTokens    += e.outputTokens    || 0;
      g.cacheReadTokens += e.cacheReadTokens  || 0;
      g.cacheWriteTokens+= e.cacheWriteTokens || 0;
      g.estimatedCostUSD+= e.estimatedCostUSD || 0;
    }
    const rows = [['Role', 'Input Tokens', 'Output Tokens', 'Cache Read', 'Cache Write', 'Est. Cost USD']];
    for (const [role, g] of Object.entries(byRole).sort(([a], [b]) => a.localeCompare(b))) {
      rows.push([
        role,
        fmtTokens(g.inputTokens),
        fmtTokens(g.outputTokens),
        fmtTokens(g.cacheReadTokens),
        fmtTokens(g.cacheWriteTokens),
        fmtCost(g.estimatedCostUSD),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  // --- Section 3: Revision waste ---
  lines.push('## Revision Waste', '');
  {
    const revisionEvents = tokenEvents.filter(e => (e.iteration || 1) > 1 && REVIEW_PHASES.has(e.phase));
    if (revisionEvents.length === 0) {
      lines.push('_No revision waste in this sprint._', '');
    } else {
      const byTask = {};
      for (const e of revisionEvents) {
        const tid = e.taskId || '(unknown)';
        if (!byTask[tid]) byTask[tid] = { iterations: new Set(), inputTokens: 0, outputTokens: 0, estimatedCostUSD: 0 };
        const g = byTask[tid];
        g.iterations.add(e.iteration);
        g.inputTokens     += e.inputTokens     || 0;
        g.outputTokens    += e.outputTokens    || 0;
        g.estimatedCostUSD+= e.estimatedCostUSD || 0;
      }
      const rows = [['Task', 'Revision Iterations', 'Input Tokens', 'Output Tokens', 'Est. Cost USD']];
      for (const [tid, g] of Object.entries(byTask).sort(([a], [b]) => a.localeCompare(b))) {
        rows.push([
          tid,
          g.iterations.size,
          fmtTokens(g.inputTokens),
          fmtTokens(g.outputTokens),
          fmtCost(g.estimatedCostUSD),
        ]);
      }
      lines.push(padTable(rows), '');
    }
  }

  // --- Section 4: Model split ---
  lines.push('## Model Split', '');
  {
    const byModel = {};
    for (const e of tokenEvents) {
      const model = e.model || '(unknown)';
      if (!byModel[model]) byModel[model] = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, estimatedCostUSD: 0 };
      const g = byModel[model];
      g.inputTokens     += e.inputTokens     || 0;
      g.outputTokens    += e.outputTokens    || 0;
      g.cacheReadTokens += e.cacheReadTokens  || 0;
      g.cacheWriteTokens+= e.cacheWriteTokens || 0;
      g.estimatedCostUSD+= e.estimatedCostUSD || 0;
    }
    const rows = [['Model', 'Input Tokens', 'Output Tokens', 'Cache Read', 'Cache Write', 'Est. Cost USD']];
    for (const [model, g] of Object.entries(byModel).sort(([a], [b]) => a.localeCompare(b))) {
      rows.push([
        model,
        fmtTokens(g.inputTokens),
        fmtTokens(g.outputTokens),
        fmtTokens(g.cacheReadTokens),
        fmtTokens(g.cacheWriteTokens),
        fmtCost(g.estimatedCostUSD),
      ]);
    }
    lines.push(padTable(rows), '');
  }

  writeFile(reportPath, lines.join('\n') + '\n');
  costReportsWritten++;
}

// --- Write COLLATION_STATE.json ---
const stateData = {
  collatedAt: new Date().toISOString(),
  featureCount: allFeatures.length,
  sprintCount: targetSprints.length,
  taskCount: allTasks.filter(t => targetSprints.some(s => s.sprintId === t.sprintId)).length,
  bugCount: allBugs.length,
};
if (DRY_RUN) {
  console.log(`[dry-run] would write: ${path.relative(cwd, path.join(storeRoot, 'COLLATION_STATE.json'))}`);
} else {
  _getStore().writeCollationState(stateData);
}

const tag = DRY_RUN ? '[dry-run] ' : '';
console.log(`${tag}Collated: ${targetSprints.length} sprint(s), ${allBugs.length} bug(s) → MASTER_INDEX.md updated, ${sprintIndexesWritten} sprint INDEX(es), ${taskIndexesWritten} task INDEX(es), ${bugIndexesWritten} bug INDEX(es), ${costReportsWritten} COST_REPORT(s) written`);

// --- Purge event directory if requested ---
if (PURGE_EVENTS) {
  const relDir = path.relative(cwd, path.join(storeRoot, 'events', SPRINT_ARG));
  try {
    const result = _getStore().purgeEvents(SPRINT_ARG, { dryRun: DRY_RUN });
    if (result.fileCount === 0) {
      console.log(`${tag}Purge: no events directory found for '${SPRINT_ARG}' — nothing to delete`);
    } else if (DRY_RUN) {
      console.log(`[dry-run] would purge: ${relDir}/ (${result.fileCount} file(s))`);
    } else {
      console.log(`Purged: ${relDir}/ (${result.fileCount} event file(s) deleted)`);
    }
  } catch (err) {
    console.error(`Error: ${err.message}`);
    process.exit(1);
  }
}

} // end if (require.main === module)